### ISSUE TITLE
Bot running but not welcoming

### ISSUE THREAD

**Issue by axelmvt** [UNICT-DMI/Welcome-Bot#41]
Hi! First of all, fantastic project! 

I was able to have the bot running with the env variable on docker. But when I join a new member to a group, by default it's not greeting. Am I missing anything? 

Thanks and best regards!

**Comment by domenicoblanco** [comment]
Hi, thanks for using the bot!
The only thing could be that the bot doesn't have access to messages.
You could try to use BotFather and disabile Privacy Mode in Group Privacy.
In order to reslfresh the permissione could be mandatory to remove and add again the bot in the group

**Comment by axelmvt** [comment]
It's working!! I love it!!

I believe the issues was that I was testing with bots and not real users!!

**Comment by domenicoblanco** [comment]
Exactly, it avoids to welcome bots 😅
